create table exterior_color (
    id              int             PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    updated_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            VARCHAR(255)    NOT NULL,
    is_enabled      BOOLEAN         NOT NULL DEFAULT TRUE
);

create table interior_color (
    id              int             PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    updated_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            VARCHAR(255)    NOT NULL,
    is_enabled      BOOLEAN         NOT NULL DEFAULT TRUE
);

create table icecar (
    id              int             PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    updated_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            VARCHAR(255)    NOT NULL,
    is_enabled      BOOLEAN         NOT NULL DEFAULT TRUE,
    vin             varchar(17)     NOT NULL UNIQUE ,
    engine_number   varchar(10)     not null,
    exterior_color_id  int          REFERENCES exterior_color(id),
    interior_color_id  int          REFERENCES interior_color(id)
)