create table gearbox (
    id              int             PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    updated_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            VARCHAR(255)    NOT NULL,
    is_enabled      BOOLEAN         NOT NULL DEFAULT TRUE
);

create table fuel (
    id              int             PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    updated_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            VARCHAR(255)    NOT NULL,
    is_enabled      BOOLEAN         NOT NULL DEFAULT TRUE
);

create table icecar (
    id              int             PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    updated_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            VARCHAR(255)    NOT NULL,
    is_enabled      BOOLEAN         NOT NULL DEFAULT TRUE,
    vin             varchar(17)     NOT NULL UNIQUE ,
    engine_value    DECIMAL(2, 1)   not null,
    gearbox_id      int             REFERENCES gearbox(id),
    fuel_id         int             REFERENCES fuel(id)
)