create table car (
    id               int          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    updated_date     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name             VARCHAR(255) ,
    is_enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    vin              varchar(17)  NOT NULL UNIQUE,
    engine_number    varchar(10)  NOT NULL unique ,
    brand            varchar(255) NOT NULL,
    car_model        varchar(255) NOT NULL,
    spec             varchar(20)  NOT NULL ,
    exterior_color   varchar(20)  NOT NULL ,
    interior_color   varchar(20)  NOT NULL ,
    arrived_at       TIMESTAMP    NOT NULL ,
    ttn_number       varchar(10)  NOT NULL ,
    is_ready_for_sale boolean     default false,
    has_defects      boolean      default false
);

create table icecar (
    id              int          primary key GENERATED BY DEFAULT AS IDENTITY ,
    engine_volume   varchar(10)  NOT NULL
);

create table charging (
    id              int          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    updated_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            VARCHAR(255) ,
    is_enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    charge_date     TIMESTAMP    NOT NULL,
    car_id          int          REFERENCES car(id)
);

create table defect (
    id              int          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    updated_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            VARCHAR(255) ,
    is_enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    elimination_date TIMESTAMP   ,
    comment         varchar      ,
    car_id          int          REFERENCES car(id)
);

create table dictionary (
    id              int          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    updated_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            varchar(255) NOT NULL ,
    dictionary_type varchar(20)  NOT NULL,
    is_enabled      BOOLEAN      NOT NULL DEFAULT TRUE
)

