create table car (
   id               int          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   updated_date     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
   created_date     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
   name             VARCHAR(255) ,
   is_enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
   vin              varchar(17)  NOT NULL UNIQUE,
   brand            varchar(255) NOT NULL,
   car_model        varchar(255) NOT NULL
);

create table icecar (
    id              int          primary key GENERATED BY DEFAULT AS IDENTITY ,
    engine_volume   varchar(10)  NOT NULL
);

create table charging (
    id              int          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    updated_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            VARCHAR(255) ,
    is_enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    charge_date     TIMESTAMP    NOT NULL,
    car_id          int          REFERENCES car(id)
);

create table dictionary (
    id              int          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    updated_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            varchar(255) NOT NULL ,
    dictionary_type varchar(20)  NOT NULL,
    is_enabled      BOOLEAN      NOT NULL DEFAULT TRUE
)

